id: P132BB41A
initial_creation_type: input
source_metadata:
  title: Chokgyur Dechen Lingpa
  language: en
  description: 'The following texts are available as part of our series honouring
    the life and work of the famous tertön Chokgyur Dechen Lingpa (mchog gyur bde
    chen gling pa, 1829–1870):'
  volume:
    ab2db1c4fdc54d14a8118b5dabe160c4:
      title: 'Advice on Nonsectarianism (from Radiant Sunlight of the Victorious Ones''
        Teachings: A Brief, First-Hand Account of the Liberating Life-Story of the
        Great Emanated Treasure Revealer)'
      parent: Advice
    79fc4b6e8e9148df9f37868c696c9082:
      title: Pithy Advice on Checking One's Progress on the Path
      parent: Advice
    2a139878041c40119dae4c20fb0a99d3:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Aspiration Prayers
    fb6c517c31d2419ea78095601d6d5761:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Aspiration Prayers
    8d5714440d5944b4bcf2418967b87172:
      title: Threefold Aspiration for Rebirth in Zangdok Palri
      parent: Aspiration Prayers
    bf33b1f61f2d43efad38815f210accd8:
      title: 'Radiant Sunlight of the Victors’ Teachings: A Brief, First-Hand Account
        of the Liberating Life-Story of the Great Emanated Treasure Revealer'
      parent: Biography
    64385591945a4d9998b0a85fe378ce15:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Biography
    25ba6ddb9ffe460b9a6fe9e8a917dcdc:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chöd
    23e227e001e148e0a0cbc061f8b6e3b6:
      title: The Inexpressible, Ultimate Confession (Yeshe Kuchokma)
      parent: Confession
    9fbc2ccf94c941578c059aa66f0d5219:
      title: The Lament of Rudra
      parent: Confession
    051569619a82428b9bea7bf78cd006e5:
      title: 'Pearl Droplets of Blessings: A Prayer to the Guru Who Embodies All'
      parent: Guru Rinpoche Prayers
    eefe8bb845534a9bb6d1a983e74cca7d:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Guru Rinpoche Prayers
    09936e8caf3f4cbc92f398728f73a870:
      title: The Prayer in Six Vajra Lines
      parent: Guru Rinpoche Prayers
    8e48cb192f044d9fa3ab2a9c7abca57e:
      title: The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma)
      parent: Guru Rinpoche Prayers
    06b7ce2f7a4b4b9f835fa686db9a9925:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Guru Rinpoche Prayers
    3225c45463cd4c91a460c9df224b3c9f:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Guru Rinpoche Prayers
    e888629c1362454caafc7fd38a7b4dd9:
      title: A Concise Guru Yoga
      parent: Guru Yoga
    848b2b8f15164c719aa687e7626e824f:
      title: 'Youthfulness Gained in Vajra-like Immortality: Verses of Truth for the
        Long Life of the Perfect Masters'
      parent: Long Life Prayers
    ae710fe72fa44246ab448030e4d2c10b:
      title: 'The Concise Cleansing Offering from The Guru’s Heart Practice: Dispelling
        All Obstacles on the Path'
      parent: Offering
    54ef07b40e85476286d8e8d26851f70d:
      title: White and Red Sur Offerings That Are Very Easy to Apply
      parent: Offering
    86ade2ae948a4a36896e7571f1799fd0:
      title: 'The Excellent Bilva Tree of Auspiciousness: Praise and Prayer to Terchen
        Chokgyur Lingpa'
      parent: Praise
    3306ef84b81b4e40b708c20184c73ab3:
      title: A Prayer to the Vidyādhara Gurus
      parent: Prayers
    7c5e2921567e4acfbc21c3ff2fed7745:
      title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
      parent: Prayers
    c8e24802a9bf4bbd8f80fb7b2f40a8b2:
      title: Concise Daily Practice of Vajrasattva
      parent: Sādhanas
    83e06dab82d8474eadb259e75dc2c23f:
      title: The Single-Page Practice of the Guru of Great Bliss
      parent: Sādhanas
    b6418d1456bc4d96a753d4c256240a7d:
      title: The Twenty-Eight Commitments
      parent: Tantra
    512298fa917841769f74bf58403ebb2f:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Tsok
created_at: '2022-02-28T22:46:47.939440'
last_modified_at: '2022-02-28T22:46:47.939446'
